testbed:
  name: 'ma_new_tb'
devices:
  csr1000v-1:
      type: asr1k
      os: "iosxe"
      alias: 'helper'
      tacacs:
          login_prompt: 'login:'
          password_prompt: 'Password:'
          username: cisco
      passwords:
          tacacs: cisco
          enable: cisco
          line: cisco
      connections:
          defaults:
            class: 'unicon.Unicon'
          a:
              protocol: telnet
              ip: "172.25.192.90"
              port: 17000



